name: cd-develop

on:
  push:
    branches: [ develop ]
jobs:
  ci:
    uses: fga-eps-mds/2023-1-schedula-gerenciador-de-localidades/.github/workflows/location-ci.yml@main

  deploy:
    needs: [ ci ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY_HML}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME_HML}}
        heroku_email: ${{secrets.HEROKU_EMAIL_HML}}
        remote_branch: develop